#!/bin/bash
#
# Copyright (c) 2013-2017, Dimitri Savineau <savineau.dimitri@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG_APT="git cmake make gcc g++ libmysqld-dev libboost-all-dev zlib1g-dev libssl-dev"
PKG_RPM="git cmake make gcc gcc-c++ mysql-devel boost-devel zlib-devel openssl-devel"

LOG_FILE="$PWD/mangos-installer.log"

CMAKE="cmake"
DEBUG=0
JOBS=1

GREEN="\033[32m"
RED="\033[31m"
RESET="\033[0m"

function Usage {
    cat << EOF
Usage: $0: [OPTIONS]
      -p <path>       : Path to MaNGOS (default: /opt/mangos-<version>)
      -d              : Set in debug mode
      -j <number>     : Number of jobs for make (default: 1)
      -v <version>    : Set MaNGOS version (classic|tbc|wotlk|cata)
      -h              : Print this help
EOF
    exit 1
}

function GetOSInfo {
    if [[ -x $(which uname 2>/dev/null) ]]; then
        os_ARCH=$(uname -m)
    else
        echo "Can't get architecture"
        exit 1
    fi
    case "$os_ARCH" in
        i?86|x86_64)
            ;;
        *)
            echo "Unsupported architecture ($os_ARCH)"
            exit 1
            ;;
    esac
    if [[ -x $(which lsb_release 2>/dev/null) ]]; then
        os_VENDOR=$(lsb_release -i -s)
        os_RELEASE=$(lsb_release -r -s)
        os_CODENAME=$(lsb_release -c -s)
        os_PACKAGE="rpm"
        if [[ "$os_VENDOR" =~ (Debian|Ubuntu) ]]; then
            os_PACKAGE="deb"
        elif [[ $os_VENDOR =~ Red.*Hat ]]; then
            os_VENDOR="Red Hat"
        fi
    elif [ -r /etc/redhat-release ]; then
        os_PACKAGE="rpm"
        for os_VENDOR in "Red Hat" CentOS Fedora; do
            if [[ -n "`grep \"$os_VENDOR\" /etc/redhat-release`" ]]; then
                ver=`sed -e 's/^.* \(.*\) (\(.*\)).*$/\1\|\2/' /etc/redhat-release`
                os_CODENAME=${ver#*|}
                os_RELEASE=${ver%|*}
                os_RELEASE=${os_RELEASE%.*}
                break
            fi
        done
    elif [ -r /etc/debian_version ]; then
        os_PACKAGE="deb"
        os_VENDOR="Debian"
        os_RELEASE=$(cat /etc/debian_version)
        if [[ "$os_RELEASE" =~ ^"5.0" ]]; then
            os_CODENAME="lenny"
        elif [[ "$os_RELEASE" =~ ^"6.0" ]]; then
            os_CODENAME="squeeze"
        elif [[ "$os_RELEASE" =~ ^"7." ]]; then
            os_CODENAME="wheezy"
        elif [[ "$os_RELEASE" =~ ^"8." ]]; then
            os_CODENAME="jessie"
        else
            echo "Unsupported Debian release ($os_RELEASE)"
            exit 1
        fi
    fi
    [ "$os_VENDOR" = "Debian" ] && [ "$os_CODENAME" = "lenny" ] && PKG_APT=$(echo $PKG_APT|sed -e "s/git/git-core/")
    if [ "$os_VENDOR" = "CentOS" ]; then
        if [[ "$os_RELEASE" =~ "6" ]]; then
            PKG_RPM=$(echo $PKG_RPM|sed -e "s/cmake/cmake28/")
            CMAKE="cmake28"
            EPEL="6-8"
            VER="6"
        elif [[ "$os_RELEASE" =~ "5" ]]; then
            EPEL="5-4"
            VER="5"
        else
            echo -e "[${RED}fail${RESET}]"
            echo "Unsupported CentOS release ($os_RELEASE)"
            exit 1
        fi
    fi
    echo "-- GNU/Linux $os_VENDOR"
    echo "-- Codename : $os_CODENAME"
    echo "-- Release  : $os_RELEASE"
    echo "-- Package  : $os_PACKAGE"
    echo "-- Platform : $os_ARCH"
}

function InstallEpelRepo {
    IsPackageInstalled "wget" || YumInstall "wget"
    wget http://dl.fedoraproject.org/pub/epel/$VER/x86_64/epel-release-$EPEL.noarch.rpm >> $LOG_FILE 2>&1
    if [ $? -ne 0 ]; then
        echo -e "[${RED}fail${RESET}]"
        echo "Unable to download epel-release-$EPEL.noarch.rpm package"
        exit 1
    fi
    rpm -Uvh epel-release-$EPEL.noarch.rpm >> $LOG_FILE 2>&1
    if [ $? -ne 0 ]; then
        echo -e "[${RED}fail${RESET}]"
        echo "Unable to install epel-release-$EPEL.noarch.rpm package"
        rm -f epel-release-$EPEL.noarch.rpm
        exit 1
    fi
    rm -f epel-release-$EPEL.noarch.rpm
}

function InstallDependencies {
    echo -n "Installing dep...   "
    if [[ "$os_VENDOR" =~ (Ubuntu|Debian) ]]; then
        apt-get -q=2 update >> $LOG_FILE 2>&1
        for PKG in $PKG_APT; do
            IsPackageInstalled $PKG || AptGetInstall $PKG
        done
    elif [[ "$os_VENDOR" =~ (Red Hat|Fedora|CentOS) ]]; then
        if [ "$os_VENDOR" = "CentOS" ]; then
            IsPackageInstalled "epel-release-$EPEL" || InstallEpelRepo
        fi
        for PKG in $PKG_RPM; do
            IsPackageInstalled $PKG || YumInstall $PKG
        done
    else
        echo -e "[${RED}fail${RESET}]"
        echo "Support for $os_VENDOR is incomplete."
        exit 1
    fi
    CheckStatus
}

function IsPackageInstalled {
    if [ "$os_PACKAGE" = "deb" ]; then
        dpkg -s "$@" > /dev/null 2>&1
    elif [ "$os_PACKAGE" = "rpm" ]; then
        rpm -q "$@" > /dev/null 2>&1
    fi
}

function AptGetInstall {
    DEBIAN_FRONTEND=noninteractive \
        apt-get install --option "Dpkg::Options::=--force-confold" --assume-yes "$@" >> $LOG_FILE 2>&1
    if [ $? -ne 0 ]; then
        echo -e "[${RED}fail${RESET}]"
        echo "Unable to install $@ with apt-get"
        exit 1
    fi
}

function YumInstall {
    yum install -y "$@" >> $LOG_FILE 2>&1
    if [ $? -ne 0 ]; then
        echo -e "[${RED}fail${RESET}]"
        echo "Unable to install $@ with yum"
        exit 1
    fi
}

function GetSources {
    [ ! -d mangos ] || rm -rf mangos
    echo -n "Cloning MaNGOS...   "
    git clone $MANGOS mangos >> $LOG_FILE 2>&1
    CheckStatus
    # (ToDo) Fix bindings directory upstream
    sed -i -e "s|src/bindings|src/|g" mangos/CMakeLists.txt >> $LOG_FILE 2>&1
    MANGOS_VERSION=$(cat mangos/version.txt)
}

function ConfigureCmake {
    mkdir -p mangos/build && cd mangos/build
    echo -n "Configuration...    "
    $CMAKE .. -DCMAKE_INSTALL_PREFIX=$PREFIX -DDEBUG=$DEBUG \
        -DPCH=1 -DINCLUDE_BINDINGS_DIR=scriptdev2 >> $LOG_FILE 2>&1
    CheckStatus
}

function BuildMangos {
    echo -n "Compiling...        "
    make -j $JOBS >> $LOG_FILE 2>&1
    CheckStatus
}

function InstallMangos {
    echo -n "Installing...       "
    make install >> $LOG_FILE 2>&1
    CheckStatus
}

function CheckStatus {
    if [ $? -eq 0 ]; then
        echo -e "[${GREEN}OK${RESET}]"
    else
        echo -e "[${RED}fail${RESET}]"
        exit 1
    fi
}

while getopts 'hdj:v:p:' OPTION; do
    case "$OPTION" in
        p)
            PREFIX="$OPTARG"
            ;;
        d)
            DEBUG=1
            ;;
        j)
            JOBS="$OPTARG"
            ;;
        v)
            VERSION="$OPTARG"
            ;;
        ?)
            Usage
            ;;
    esac
done

[ -z "$VERSION" ] && Usage

[ -f $LOG_FILE ] && rm -f $LOG_FILE

if [[ "$VERSION" =~ ^(classic|tbc|wotlk|cata)$ ]]; then
    MANGOS=git://github.com/cmangos/mangos-$VERSION.git
    [ "$VERSION" = "cata" ] && PKG_APT+=" libbz2-dev" && PKG_RPM+=" bzip2-devel"
    [ -z "$PREFIX" ] && PREFIX="/opt/mangos-$VERSION"
else
    echo "$VERSION is not a MaNGOS version"
    exit 1
fi

GetOSInfo
InstallDependencies
GetSources
ConfigureCmake
BuildMangos
InstallMangos
echo "MaNGOS $MANGOS_VERSION ($VERSION) has been installed !"

exit 0
